language: python
python: 3.6
env:
  # Keep this list up to date using `tox -l`
  matrix:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=py36-flake8
    - TOXENV=py36-docs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libssl-dev libxmlsec1-dev
install: travis_retry pip install tox coveralls
script: tox -e $TOXENV -v
after_success: coveralls
