language: python

env:
  # Keep this list up to date using `tox -l`
  matrix:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=flake8
    - TOXENV=docs

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libssl-dev libxmlsec1-dev

install: travis_retry pip install tox coveralls

script: tox -e $TOXENV

after_success: coveralls
