language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev libssl-dev libxmlsec1-dev
install:
  - travis_retry pip install coveralls tox-travis
script: tox -v
after_success: coveralls
